#!/bin/sh -e

make

mkdir -pv $1/usr/include
mkdir -pv $1/usr/lib
mkdir -pv $1/usr/bin

cp inc/* $1/usr/include/
cp build/libbearssl.a $1/usr/lib/
cp build/libbearssl.so $1/usr/lib/
cp build/brssl $1/usr/bin/
